export const INFECTION_STATUS = 'INFECTION_STATUS';
export const INFECTION_STATUS_SUCCESS = 'INFECTION_STATUS_SUCCESS';
export const INFECTION_STATUS_ERROR = 'INFECTION_STATUS_ERROR';

export const INFECTION_STATUS_ONE = 'INFECTION_STATUS_ONE';
export const INFECTION_STATUS_ONE_SUCCESS = 'INFECTION_STATUS_ONE_SUCCESS';
export const INFECTION_STATUS_ONE_ERROR = 'INFECTION_STATUS_ONE_ERROR';



export const AGEGENDER_STATUS = 'AGEGENDER_STATUS';
export const AGEGENDER_STATUS_SUCCESS = 'AGEGENDER_STATUS_SUCCESS';
export const AGEGENDER_STATUS_ERROR = 'AGEGENDER_STATUS_ERROR';



export const FOREIGN_STATUS = 'FOREIGN_STATUS';
export const FOREIGN_STATUS_SUCCESS = 'FOREIGN_STATUS_SUCCESS';
export const FOREIGN_STATUS_ERROR = 'FOREIGN_STATUS_ERROR';



export const HOSPITAL_STATUS = 'HOSPITAL_STATUS';
export const HOSPITAL_STATUS_SUCCESS = 'HOSPITAL_STATUS_SUCCESS';
export const HOSPITAL_STATUS_ERROR = 'HOSPITAL_STATUS_ERROR';



export const REGION_STATUS = 'REGION_STATUS';
export const REGION_STATUS_SUCCESS = 'REGION_STATUS_SUCCESS';
export const REGION_STATUS_ERROR = 'REGION_STATUS_ERROR';

export const REGION_STATUS_TODAY = 'REGION_STATUS_TODAY';
export const REGION_STATUS_TODAY_SUCCESS = 'REGION_STATUS_TODAY_SUCCESS';
export const REGION_STATUS_TODAY_ERROR = 'REGION_STATUS_TODAY_ERROR';



export const SAFETYNEWS_STATUS = 'SAFETYNEWS_STATUS';
export const SAFETYNEWS_STATUS_SUCCESS = 'SAFETYNEWS_STATUS_SUCCESS';
export const SAFETYNEWS_STATUS_ERROR = 'SAFETYNEWS_STATUS_ERROR';